### ISSUE TITLE
The issue of semicolons affecting the lifecycle

### ISSUE THREAD

**Issue by naqunmiemie** [jinxdash/prettier-plugin-rust#22]
### Input code

```rust
if let Some(left) = node.borrow().left.as_ref() {
                    deque.push_back(left.clone());
                };
                if let Some(right) = node.borrow().right.as_ref() {
                    deque.push_back(right.clone());
                };
```

### Output code

```rust
if let Some(left) = node.borrow().left.as_ref() {
                    deque.push_back(left.clone());
                }
                if let Some(right) = node.borrow().right.as_ref() {
                    deque.push_back(right.clone());
                }
```

### Additional context

![image](https://github.com/jinxdash/prettier-plugin-rust/assets/45996643/bc3e76ec-5ea0-48ae-84d7-3bb8cd9f660b)
![image](https://github.com/jinxdash/prettier-plugin-rust/assets/45996643/c13e85d0-1783-4224-8112-ec803a255d11)

**Comment by jinxdash** [comment]
Related: https://github.com/rust-lang/rust/issues/70844

Per Rust "spec" those IfLet blocks are statements, hence semicolons should be meaningless and unnecessary. 

My understanding is that this is a longstanding bug within Rust whereby "if let" is syntax sugar that gets unrolled into some code that itself is missing a semicolon.

I'm inclined to say that the formatting is correct and that the issue is upstream. Maybe someone can correct me on that, otherwise I'd suggest adding `// prettier-ignore` above the `for in` block
