### ISSUE TITLE
The formatting of the `use` statement is different from cargo-fmt

### ISSUE THREAD

**Issue by timongh** [jinxdash/prettier-plugin-rust#27]
### Input code

```rust
`use std::io::{   stdin  ,    stdout  ,   Write   };`
```

### Output code

```rust
`use std::io::{ stdin, stdout, Write };`
```

### Additional context

The results generated by executing `cargo fmt`: `use std::io::{stdin, stdout, Write};`

**Comment by jinxdash** [comment]
All style decisions are adapted from Prettier core (typescript), so differences from rustfmt are expected

Note that you can also use prettier in the CLI (requires NodeJS):
```
npm install --global prettier-plugin-rust prettier
```
Then instead of `cargo fmt`, you can format your project using this command:
```
prettier --write **/*.rs
```
 https://github.com/jinxdash/prettier-plugin-rust#project-integration
